#ifndef _RRTVMS_COMMAND__
#define _RRTVMS_COMMAND__

typedef enum __enum_from_avs_to_avsproxy_request_type__
{
	REQUEST_FROM_AVS_TO_AVSPROXY_USERS_INFO,
	REQUEST_FROM_AVS_TO_AVSPROXY_MOD_USER_MEDIA,
	REQUEST_FROM_AVS_TO_AVSPROXY_ADD_USER,
	REQUEST_FROM_AVS_TO_AVSPROXY_DEL_USER,
	REQUEST_FROM_AVS_TO_AVSPROXY_MEDIA_STREAM
} enum_from_avs_to_avsproxy_request_t;

typedef enum __enum_from_avsproxy_to_avs_request_type__
{
	REQUEST_FROM_AVSPROXY_TO_AVS_LOGIN = 60,
	REQUEST_FROM_AVSPROXY_TO_AVS_LOGOUT,
	REQUEST_FROM_AVSPROXY_TO_AVS_LINK_USER,
	REQUEST_FROM_AVSPROXY_TO_AVS_UNLINK_USER
} enum_from_avsproxy_to_avs_request_t;

typedef enum __enum_from_client_to_avsproxy_request_type__
{
	REQUEST_FROM_CLIENT_TO_AVSPROXY_LOGIN,
	REQUEST_FROM_CLIENT_TO_AVSPROXY_LOGOUT,
	REQUEST_FROM_CLIENT_TO_AVSPROXY_LINK_ROOM_USER,
	REQUEST_FROM_CLIENT_TO_AVSPROXY_UNLINK_ROOM_USER
} enum_from_client_to_avsproxy_request_t;

typedef enum __enum_from_avsproxy_to_client_request_type__
{
	REQUEST_FROM_AVSPROXY_TO_CLIENT_ROOMS_INFO,
	REQUEST_FROM_AVSPROXY_TO_CLIENT_ROOM_ADD_USER,
	REQUEST_FROM_AVSPROXY_TO_CLIENT_ROOM_DEL_USER
} enum_from_avsproxy_to_client_request_t;

typedef enum __enum_media_mask_type__
{
	MEDIA_MASK_AUDIO = 0x01,
	MEDIA_MASK_VIDEO = 0x02,
} enum_media_mask_t;

typedef enum __enum_rtp_payload_type__
{
	RTP_G7231_AUDIO_PAYLOAD_TYPE = 0,
	RTP_MPEG4_VIDEO_PAYLOAD_TYPE,
	RTP_MP3_AUDIO_PAYLOAD_TYPE,
	RTP_H263_VIDEO_PAYLOAD_TYPE,
	RTP_VCM_VIDEO_PAYLOAD_TYPE,
	RTP_DIVX_VIDEO_PAYLOAD_TYPE,
	RTP_G7221_AUDIO_PAYLOAD_TYPE,
	RTP_G729a_AUDIO_PAYLOAD_TYPE,
	RTP_GSM6_AUDIO_PAYLOAD_TYPE,
	RTP_JPEG2K_VIDEO_PAYLOAD_TYPE,
	RTP_X264_VIDEO_PAYLOAD_TYPE,
	RTP_ACC_AUDIO_PAYLOAD_TYPE,
	RTP_NELLY_AUDIO_PAYLOAD_TYPE = 14,
	RTP_X264_VIDEO_CODEC_PAYLOAD_TYPE = 29,
	RTCP_PAYLOAD_TYPE = 100,
	RTCP_RR_PAYLOAD_TYPE,						// Recevier report
	RTCP_SD_PAYLOAD_TYPE,						// Source Description
	RTCP_GB_PAYLOAD_TYPE,						// Good bye
	RTCP_UD_PAYLOAD_TYPE,						// User Data
	RTCP_LOST_PACKAGE_PAYLOAD_TYPE,
	RTCP_MIC_NOTIFY_ID_PAYLOAD_TYPE,
	RTCP_PACK_LOST_ID2_PAYLOAD_TYPE,
	RTP_EXPAND_PAYLOAD_TYPE = 110,
	RTCP_SEND_REPORT_PAYLOAD_TYPE = 200,
	RTCP_RECV_REPORT_PAYLOAD_TYPE
} enum_rtp_payload_t;

#endif
